# This is a basic workflow to help you get started with Actions

name: CI Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Installing
        working-directory: packages/web
        run: npm install

      - name: Running Front-end Unit tests
        working-directory: packages/web
        run: npm run test
      - name: Running Front-end E2E tests
        working-directory: packages/web
        # run: npm run e2e:ci
        run: |
          npm run start:ci
          npm run e2e:ci
